GET http://localhost:8080//exam/java/add?question=who&answer=I

###

GET http://localhost:8080//exam/java/add?question=who?&answer=I!

###

GET http://localhost:8080//exam/math/add?question=who??&answer=I!!

###

GET http://localhost:8080//exam/math/add?question=who???&answer=I!!!

###

GET http://localhost:8080//exam/java/

###

GET http://localhost:8080//exam/math/

###

GET http://localhost:8080//exam/java/remove?question=who&answer=I

###

GET http://localhost:8080//exam/java/

###

GET http://localhost:8080//exam/java/remove?question=who&answer=I

###

GET http://localhost:8080//?amount=2

###